### ISSUE TITLE
Question about finite difference taps

### ISSUE THREAD

**Issue by Ice-Tear** [NVlabs/neuralangelo#12]
Hi~Thanks for the great work and provided code!
Is there any difference in the accuracy of finite difference when taps is equal to 6 and 4? Will taps=6 be more accurate? Because it is 6 in the paper, but it is 4 by default in the code.

**Comment by mli0603** [comment]
Hi @Ice-Tear 

Thank you for your interest in the project.

The original implementation reported in the paper used 6 taps for finite differences. We have since then optimized the runtime of the code. By using 4 points, we improved the per-iteration training by ~27%, and we didn't observe performance drops. I hope this helps!
