### ISSUE TITLE
Strange curvature loss

### ISSUE THREAD

**Issue by nicetryzz** [NVlabs/neuralangelo#172]
Thanks for your work! I test the meeting room in tank and temples datasets. The training curvature loss is strange. It increases a lot when reduces curvature weight. Should I increase the curvature weight?

curvature loss:
![W B Chart 2023_12_18 13_18_55](https://github.com/NVlabs/neuralangelo/assets/70940473/cd998497-1243-4776-b616-2053a8e24452)

I test in 4 16G Tesla P100. Parameter as below:
* dict_size: 21
* dim: 8
* training batch size: 2

**Comment by mli0603** [comment]
Hi @nicetryzz 

This is expected. As the numerical gradient step becomes smaller, more geometric details are generated due to coarse-to-fine control, which means larger curvature weight. If you want smoother surface, increasing the curvature weight would help at the cost of details. I hope this helps!
