### ISSUE TITLE
Object masks for DTU scan 83

### ISSUE THREAD

**Issue by hanyucc** [NVlabs/neuralangelo#184]
As mentioned in the paper, the IDR object masks for scan 83 are incorrect. Are there plans to release the manually annotated masks that you use for the evaluation results in the supplement? Thanks!

**Comment by mli0603** [comment]
Hi @hanyucc 

Please find the reannotated DTU masks in this link: https://drive.google.com/drive/folders/1RpjghBc791c3RIvRro7c0rJ6Hf7TZqZV?usp=sharing

**Comment by hanyucc** [comment]
Thanks! Just to confirm, I know that you report the results with the reannotated masks for scan 83 in the supplement. Are the result for scan 105 with the reannotated masks reported somewhere? I assume the numbers in the main paper are with the original masks

**Comment by mli0603** [comment]
Hi @hanyucc 

Good catch, I thought 105 was included in the supplement but apparently not... This is probably because scan 105 was annotated much later and I forgot to include it in the supplement. I will remove the 105 masks in the link so people won't get confused in the future. 

And you are right, the numbers in the main paper are with the original masks.
