### ISSUE TITLE
Exporting mesh with texture

### ISSUE THREAD

**Issue by smtabatabaie** [NVlabs/neuralangelo#9]
Hi, I could run the training and export the ply file, I wanted to ask if it is possible with Neuralangelo to export a 3d model with texture. 
Thanks

**Comment by mli0603** [comment]
Hi @smtabatabaie 

Thank you for your interest in the project. 

Because some objects will have view-dependent effects (I.e., colours will look different), we did not provide a functionality for exporting textures but rather separate the functionalities of rendering images and exporting meshes.

I agree that textured mesh is of interest for lots of people and this is something on our todo list :)

**Comment by qume** [comment]
You may be able to use the texturing component of Meshroom to texture the mesh from this project:
https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/nodes/Texturing.html

**Comment by RishabhBajaj25** [comment]
Congratulations on the amazing work and for making it public! May I add on a follow up to that? Why is the rendered file mentioned as mesh and not point cloud since the ply is not a triangular mesh? Is the point cloud derived from the mesh? Additionally, are there plans of adding the functionality for exporting a colourized point cloud?

**Comment by mli0603** [comment]
Hi @RishabhBajaj25 

By default the 3D shape is represented as an iso-surface mesh. We could additionally add texturing support, which is part of our ongoing work. If you want to convert the mesh to a point cloud, you could just keep the vertices/rgb values.

**Comment by RishabhBajaj25** [comment]
I see. Thanks for your quick response. From my limited experience, once SDF has been trained, marching cubes extracts the isosurface. How would I extract the rgb values for the points samples on the isosurface?

**Comment by mli0603** [comment]
Hi @RishabhBajaj25 

You could use the vertex locations to directly query the color network. I am not sure how good the results will be as this is very ad hoc. We are looking into this to support colored-mesh generation.

**Comment by RishabhBajaj25** [comment]
Got it. Thanks for your response.

**Comment by mli0603** [comment]
Please see https://github.com/NVlabs/neuralangelo/pull/45
